### ISSUE TITLE
[insight.md] Typos: 请华大学 -> 清华大学

### ISSUE THREAD

**Issue by hellozimo** [kaiyuanshe/2019-China-Open-Source-Report#2]
请确认 [insight.md](https://github.com/kaiyuanshe/2019-China-Open-Source-Report/blob/master/insight.md) 中的 “请华大学” 错别字，以及图片 [images/4-insight-30.png](https://github.com/kaiyuanshe/2019-China-Open-Source-Report/blob/master/images/4-insight-30.png) 中的 “请华大学”。

**Comment by bestony** [comment]
merged

**Comment by hellozimo** [comment]
@bestony 图片 [images/4-insight-30.png](https://github.com/kaiyuanshe/2019-China-Open-Source-Report/blob/master/images/4-insight-30.png) 中的 “请华大学” 没有修改过来，我们有找到截图的文章。
